"""Creating doctor table

Revision ID: 36af4ba651c8
Revises: 2990bf068dd1
Create Date: 2025-03-30 17:28:25.911266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36af4ba651c8'
down_revision = '2990bf068dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctors')
    # ### end Alembic commands ###
